# Generated by Django 3.2.1 on 2021-06-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Service Title', max_length=200)),
                ('description', models.TextField(help_text='Enter Product Description')),
                ('price', models.CharField(help_text='Enter Product price', max_length=20)),
            ],
        ),
    ]
