# Generated by Django 3.2.1 on 2021-06-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.CharField(default='computerService', help_text='Enter Product group', max_length=20),
        ),
    ]
