# Generated by Django 3.2.1 on 2021-06-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
