# Generated by Django 3.2.1 on 2021-06-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(help_text='Enter Service Title', max_length=200, null=True),
        ),
    ]
