# Generated by Django 3.2.1 on 2021-06-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_cart_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
    ]
