# Generated by Django 3.2.1 on 2021-06-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_cart_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='عالی است', max_length=200),
        ),
    ]
